[package]
name = "axum-san"
version = "0.2.0"
edition = "2024"
publish = false

[profile.release]
lto = true
strip = true
debug = false
codegen-units = 1
opt-level = "s"


[dependencies]
axum = { version = "~0.8" }
tokio = { version = "^1", features = ["full"] }

